version: "3.9"
services:
  bot:
    image: leastrio/anti-ghost-ping
    depends_on:
      - database
    env_file:
      - config.env
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}